namespace DomainLayer.ValueObjects;

public class Password
{
    public string Hash { get; private set; }

    private Password(string hash)
    {
        if (string.IsNullOrWhiteSpace(hash))
            throw new ArgumentException("Password hash cannot be null or empty", nameof(hash));

        Hash = hash;
    }

    public static Password Create(string plainPassword)
    {
        if (string.IsNullOrWhiteSpace(plainPassword))
            throw new ArgumentException("Password cannot be null or empty", nameof(plainPassword));

        if (plainPassword.Length < 6)
            throw new ArgumentException("Password must be at least 6 characters long", nameof(plainPassword));

        // The hash will be generated by the infrastructure layer using proper hashing
        throw new InvalidOperationException("Use Password.FromHash() to create a Password from an existing hash");
    }

    public static Password FromHash(string hash)
    {
        return new Password(hash);
    }

    public override bool Equals(object? obj)
    {
        if (obj is Password other)
            return Hash == other.Hash;

        return false;
    }

    public override int GetHashCode()
    {
        return Hash.GetHashCode();
    }

    public override string ToString()
    {
        return "[REDACTED]";
    }
}
